Adding queryGenerator options to mongoose-batches
charliemitchell/mongoose-batches pull request #1
Opened 2019-07-11 19:30 UTC by vickenstein

With mongoose models we can pre-define queries on the model
e.g.
```javascript
Schema.query.byName = function(name) { return this.where({ name })}
``` 
Sometimes those logics can be very complex thus to increase maintainability - the queryGenerator option will allow one to utilize these functions with mongoose-batches.

2019-07-11 20:52 UTC, charliemitchell requested changes

2019-07-11 20:52 UTC, charliemitchell commented on index.js
> +      var countQuery = this.find(find);
Very cool. Can you make a few stylistic changes.

```
var query = this.find(find);
var countQuery = this.find(find);

if (opts.queryGenerator) {
  query = opts.queryGenerator(query);
  countQuery = opts.queryGenerator(countQuery);
}

countQuery.count().exec(function (err, count) {
```

2019-07-11 20:52 UTC, charliemitchell commented on .gitignore
> +node_modules
Thank you.

2019-07-12 16:56 UTC, vickenstein commented on .gitignore
> +node_modules
chyeah

2019-07-12 22:30 UTC, charliemitchell approved these changes

2019-07-12 22:30 UTC, merged